require_relative 'schema/attribute'
require_relative 'schema/base'
require_relative 'schema/any_of'
require_relative 'schema/array_of'
require_relative 'schema/empty'
require_relative 'schema/any'
require_relative 'schema/resource'
require_relative 'schema/resource_array_of'
